# Generated by Django 5.1.3 on 2024-12-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_is_sale_product_sale_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
