# Generated by Django 5.1.3 on 2024-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="phone",
            field=models.CharField(default="01011111111", max_length=255),
            preserve_default=False,
        ),
    ]
